### ISSUE TITLE
Integration tests failing now and then

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/releases#7] opened 2020-08-19 06:28 UTC
We get this error from time to time at the end of the tasks:

```
...
RTNETLINK answers: No such process
Check if SSH login to firewall works
kex_exchange_identification: read: Connection reset by peer
```

https://github.com/metal-stack/releases/runs/998699677

**Comment by Gerrit91** [comment] 2020-08-24 08:12
I temporarily disabled the SSH test, which muted the problem for now.

**Comment by majst01** [comment] 2020-09-17 12:42
duplicate of https://github.com/metal-stack/mini-lab/issues/37

**Closed by majst01** 2020-09-17 12:42 UTC
